# Generated by Django 5.0 on 2023-12-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_ng', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='Auth_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
