# Generated by Django 5.0 on 2023-12-12 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_ng', '0002_author_auth_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='Auth_id',
        ),
    ]
