# Generated by Django 5.0 on 2023-12-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_ng', '0002_remove_data_2023_title_data_2023_jil'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_2023',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
