# Generated by Django 5.0 on 2023-12-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_ng', '0003_remove_author_auth_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='description_author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
