# Generated by Django 5.0 on 2023-12-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_ng', '0003_data_2023_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_2023',
            name='jil',
        ),
        migrations.AlterField(
            model_name='data_2023',
            name='title',
            field=models.CharField(blank=True, choices=[(2019, 'MNNOG1'), (2020, 'MNNOG2')], max_length=32, null=True),
        ),
    ]
