# Generated by Django 5.0 on 2023-12-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_ng', '0004_author_contact_author_description_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profile',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='images/'),
        ),
    ]
