# Generated by Django 5.0 on 2023-12-12 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_ng', '0005_author_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_2023',
            name='Author_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_app_ng.author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='description_author',
            field=models.CharField(blank=True, max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='data_2023',
            name='description',
            field=models.TextField(blank=True, max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='data_2023',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='related_papers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ng_papers', models.CharField(max_length=100, null=True)),
                ('description_ng_papers', models.TextField(blank=True, max_length=360, null=True)),
                ('published_ng_papers', models.DateField(blank=True, default=None, null=True)),
                ('is_published_ng_papers', models.BooleanField(default=False)),
                ('attach_ng_papers', models.FileField(blank=True, null=True, upload_to='covers/')),
                ('Author_id_ng_papers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_app_ng.author')),
            ],
        ),
    ]
