# Generated by Django 5.0 on 2023-12-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_ng', '0005_alter_data_2023_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_2023',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='data_2023',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='data_2023',
            name='picture',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='data_2023',
            name='published',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
