# Generated by Django 5.0 on 2023-12-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_ng', '0006_data_2023_author_id_alter_author_description_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='images_author/'),
        ),
        migrations.AlterField(
            model_name='data_2023',
            name='picture',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='images_data/'),
        ),
        migrations.AlterField(
            model_name='related_papers',
            name='attach_ng_papers',
            field=models.FileField(blank=True, null=True, upload_to='covers_ng_papers/'),
        ),
    ]
