# Generated by Django 5.0 on 2023-12-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_ng', '0006_data_2023_cover_data_2023_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_2023',
            name='published',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
