# Generated by Django 5.0 on 2023-12-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_ng', '0007_alter_data_2023_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_2023',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
