# Generated by Django 5.0 on 2023-12-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_ng', '0008_data_2023_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_2023',
            name='published',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
