# Generated by Django 5.0 on 2023-12-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_ng', '0008_alter_related_papers_author_id_ng_papers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_2023',
            name='title',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
