# Generated by Django 5.0 on 2023-12-14 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_ng', '0009_alter_data_2023_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_2023',
            name='title',
            field=models.CharField(max_length=100, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=1, message='Title cannot be empty.')]),
        ),
    ]
