# Generated by Django 5.0 on 2023-12-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_ng', '0010_alter_data_2023_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_2023',
            name='title',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
