# Generated by Django 5.0 on 2023-12-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_ng', '0011_alter_data_2023_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_2023',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
