# Generated by Django 5.0 on 2023-12-18 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_ng', '0013_alter_data_2023_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_2023',
            name='is_approved',
        ),
    ]
