# Generated by Django 5.0 on 2023-12-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_ng', '0014_remove_data_2023_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_2023',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
