# Generated by Django 5.0 on 2024-01-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_ng', '0015_data_2023_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_2023',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='related_papers',
            name='description_ng_papers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
