# Generated by Django 5.0 on 2024-01-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_ng', '0016_alter_data_2023_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='related_papers',
            name='picture',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='images_data_mnnog/'),
        ),
    ]
