# Generated by Django 5.0 on 2024-01-10 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_ng', '0017_related_papers_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='related_papers',
            old_name='picture',
            new_name='picture_mnnog',
        ),
    ]
